# Generated by Django 3.2 on 2021-05-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, verbose_name='앨범명')),
                ('released_at', models.DateTimeField(verbose_name='발매일')),
                ('description', models.TextField(null=True, verbose_name='상세설명')),
            ],
            options={
                'db_table': 'albums',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='아티스트명')),
                ('type', models.CharField(choices=[('G', 'group'), ('S', 'solo')], default='S', max_length=2, verbose_name='아티스트타입')),
                ('group', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='musics.artist')),
            ],
            options={
                'db_table': 'artists',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32, verbose_name='제목')),
                ('lyrics', models.TextField(null=True, verbose_name='가사')),
                ('album', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='musics.album')),
                ('artist', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='musics.artist')),
                ('genre', models.ManyToManyField(db_constraint=False, null=True, to='musics.Genre')),
            ],
            options={
                'db_table': 'songs',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='musics.artist'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['deleted_at'], name='songs_deleted_9b922c_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['album'], name='songs_album_i_26cc10_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist'], name='songs_artist__37c281_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['deleted_at'], name='artists_deleted_318af7_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['type'], name='artists_type_cbe6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['deleted_at'], name='albums_deleted_aed691_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist'], name='albums_artist__2d0263_idx'),
        ),
    ]
