# Generated by Django 3.2 on 2021-05-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32, verbose_name='제목')),
                ('lyrics', models.TextField(null=True, verbose_name='가사')),
                ('number', models.PositiveIntegerField(verbose_name='순서')),
                ('represent', models.BooleanField(default=False, verbose_name='타이틀곡')),
                ('play_time', models.CharField(max_length=8, verbose_name='재생시간')),
            ],
            options={
                'db_table': 'tracks',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveIndex(
            model_name='album',
            name='albums_deleted_aed691_idx',
        ),
        migrations.RemoveIndex(
            model_name='album',
            name='albums_artist__2d0263_idx',
        ),
        migrations.RemoveIndex(
            model_name='artist',
            name='artists_type_cbe6ce_idx',
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.URLField(null=True, verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='artist',
            name='debut',
            field=models.DateField(null=True, verbose_name='데뷔일'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(to='musics.Genre'),
        ),
        migrations.AddField(
            model_name='artist',
            name='thumbnail',
            field=models.URLField(null=True, verbose_name='썸네일'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['deleted_at', 'artist'], name='albums_deleted_b6c039_idx'),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='musics.album'),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='musics.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.ManyToManyField(db_constraint=False, null=True, to='musics.Genre'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['deleted_at', 'artist'], name='tracks_deleted_b9863a_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['album'], name='tracks_album_i_8d2ff6_idx'),
        ),
    ]
